variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
services:
  - docker:dind

stages:          
  - build

build-job:     
  stage: build
  image: docker:dind
  tags:
    - django
  script:
    - ls -la
    - echo $CI_COMMIT_SHORT_SHA
    - echo $CI_REGISTRY_IMAGE
    - docker build -t CI_REGISTRY_IMAGE:CI_COMMIT_SHORT_SHA .
    - docker push CI_REGISTRY_IMAGE:CI_COMMIT_SHORT_SHA

build-job1:      
  stage: build
  tags:
    - django
  script:
    - docker info
    - echo "Compile complete."

