include:
   - project: 'chumkaska1/template'
     ref: master
     file: template_build.yml


services:
  - docker:dind

stages:          
  - build
  - test
  - run
.job_template: &job_run
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose up -d

build-dev:     
  stage: build
  image: docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  tags:
    - django
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:dev$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:dev$CI_COMMIT_SHORT_SHA
  rules:
    - if: $CI_COMMIT_REF_NAME == 'dev'


build-prod:     
  stage: build
  image: docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  tags:
    - django
  extends: template_build
  rules:
    - if: $CI_COMMIT_REF_NAME == 'master'


run-compose-dev:     
  stage: run
  tags:
    - django_shell
  variables:
    IMAGE_WEB: dev
  <<: *job_run
  rules:
    - if: $CI_COMMIT_REF_NAME == 'dev'


run-compose-prod:      
  stage: test
  tags:
    - django_shell
  variables:
    IMAGE_WEB: prod
  script:
    - cat aaa
  rules:
    - if: $CI_COMMIT_REF_NAME == 'master'
