services:
  db:
    image: postgres:13.0-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network

  web:
    build: .
    restart: always
    command: gunicorn Blog.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - django_network

  nginx:
    image: nginx:1.29-alpine
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx/django.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:
    driver: bridge
